"use client";

import { useMemo } from "react";
import { formatHoursShort } from "@/lib/format";
import { ReportTable, columnKey } from "@/components/report-table";
import type { ReportSnapshot } from "@/lib/types";

/**
 * Client-facing snapshot view. The snapshot arrives already sanitized by the
 * server (see page.tsx `sanitizeSnapshot`) — admin-hidden tasks and columns are
 * gone from the data entirely, so there is no reveal/toggle here: the client
 * physically cannot see hidden rows/columns. `hiddenColumns` only ever carries
 * the leading estimate/total columns, whose values were already nulled.
 */
export function PublicReportView({
  clientName,
  clientColor,
  snapshot,
  publishedAt,
  hiddenColumns,
}: {
  clientName: string;
  clientColor: string;
  snapshot: ReportSnapshot;
  publishedAt: string | null;
  hiddenColumns: string[];
}) {
  const lastUpdated = publishedAt
    ? new Date(publishedAt).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })
    : null;

  // per-period charged totals for the invoices pane (all tasks are visible)
  const periodSummary = useMemo(() => {
    const tasks = snapshot.sections.flatMap((s) => s.tasks);
    return snapshot.periods.map((p, i) => ({
      ...p,
      minutes: tasks.reduce((s, t) => s + (t.periodMinutes[i] ?? 0), 0),
    }));
  }, [snapshot]);

  return (
    <main className="mx-auto max-w-6xl p-6 md:p-10">
      <header className="mb-6 flex items-start justify-between gap-4">
        <div className="flex items-center gap-3">
          <span
            className="flex size-11 items-center justify-center rounded-xl text-lg font-bold text-white"
            style={{ backgroundColor: clientColor }}
          >
            {clientName[0]}
          </span>
          <div>
            <h1 className="text-2xl font-bold tracking-tight">{clientName}</h1>
            <p className="text-sm text-muted">
              Hours report{lastUpdated && <> · last updated {lastUpdated}</>}
            </p>
          </div>
        </div>
        <span
          className="brand-wordmark h-5 w-32 shrink-0"
          style={{ backgroundColor: "#0b43ed" }}
          role="img"
          aria-label="Studio&more"
        />
      </header>

      <div className="grid items-start gap-4 lg:grid-cols-4">
        <div className="rounded-2xl border border-border bg-surface p-4 lg:col-span-3">
          <ReportTable snapshot={snapshot} hiddenColumns={hiddenColumns} hiddenTaskIds={[]} />
        </div>

        <aside className="flex flex-col gap-3">
          <div className="rounded-2xl border border-border bg-surface p-4">
            <h2 className="mb-2 text-xs font-medium uppercase tracking-wide text-faint">
              Billing periods
            </h2>
            {periodSummary.length === 0 && (
              <p className="text-sm text-faint">No payment periods defined.</p>
            )}
            <div className="flex flex-col gap-2">
              {periodSummary
                .filter((p, i) => !hiddenColumns.includes(columnKey(i)))
                .map((p) => (
                  <div key={p.label} className="rounded-lg bg-background p-2.5 text-sm">
                    <div className="flex items-center justify-between">
                      <span className="font-medium">{p.label}</span>
                      <span className="font-semibold tabular-nums">{formatHoursShort(p.minutes)}</span>
                    </div>
                    <div className="mt-0.5 text-xs text-muted">
                      {p.hourCap != null && <span>cap {p.hourCap}h</span>}
                      {p.hourCap != null && p.advanceHours != null && " · "}
                      {p.advanceHours != null && <span>advance {p.advanceHours}h</span>}
                      {p.hourCap == null && p.advanceHours == null && (
                        <span>
                          {p.from} → {p.to}
                        </span>
                      )}
                    </div>
                  </div>
                ))}
            </div>
          </div>
          <p className="px-1 text-center text-[11px] text-faint">
            Generated by Studio&amp;more · updated only when the studio publishes a new version.
          </p>
        </aside>
      </div>
    </main>
  );
}
